### ISSUE TITLE
Toast not working on modal view

### ISSUE THREAD

**Issue by baretka** [triniwiz/nativescript-toasty#12]
Toast allways show behind modal view when called.
Platform: ios
Version: 4.2.4
We tried: 
https://github.com/triniwiz/nativescript-toasty/pull/11
it did not fix problem. Toast still showing behind modal view

**Comment by bradmartin** [comment]
Closed with 1.3.0 release

**Comment by luffyzc** [comment]
toast still show behind modal view in Ipad, but works in iphone
