### ISSUE TITLE
[IOS] : Tosty displayed below Tabview buttons !

### ISSUE THREAD

**Issue by kefahB** [triniwiz/nativescript-toasty#16]
Hi, 

I have a Page with `Tabview` and on `tab 1` I have a `scroll view` .. when Toasty is showing .. it appear below the Tab View Buttons.

I try to provide playground with the structure but I have crash [Please see here](https://play.nativescript.org/?template=play-tsc&id=Un4J50&v=2)

Thanks

**Comment by bradmartin** [comment]
version 2.0.0 of the plugin now provides an object to pass in `ios` specific configuration and you can set the `anchorView` for the Toast to "anchor" itself too. In this case, you might want to pass in  an instance of the `tabview.ios` (need to provide the native iOS instance for this to work). See the demo `main.ts` for example on this and the README as well.
