### ISSUE TITLE
NativeScript Vue

### ISSUE THREAD

**Issue by RishatM** [triniwiz/nativescript-toasty#22]
Is this compatible with NativeScript Vue?
tns-core-modules  ~5.4.0
tns-ios: 6.0.0

I tried importing this in several ways, in my app.js, in an actual component, but every time I try to use it my app crashes with an error: 
CONSOLE ERROR file:///app/vendor.js:23387:20: [Vue warn]: Error in mounted hook: "TypeError: undefined is not an object (evaluating 'frame$$1.id')"
found in
---> <Page>
<Anonymous>
<Frame>
<Root>

This might be me trying to import it the wrong way. I am not using TypeScript. What is correct way to import and use this with NS Vue?

**Comment by lochstar** [comment]
Works fine with NativeScript-Vue with the usage instructions in the README.
