### ISSUE TITLE
iOS toasts do not respect safeArea on iPhone 'X' style devices

### ISSUE THREAD

**Issue by kfisto** [triniwiz/nativescript-toasty#29]
When positioned at the bottom, Toasts border the home indicator; when positioned at the top, they appear half behind the notch. This does not happen in the Toast sample app (v 3.1).

**Comment by armpogart** [comment]
@kfisto If you have a spare time, check whether the pull request works for your case either, as I have tested for my simple usage.

**Comment by kfisto** [comment]
@armpogart Sorry for the delay, I've verified that the PR solves the issue. Thanks!
