### ISSUE TITLE
Android Rounded Toast

### ISSUE THREAD

**Issue by CatchABus** [triniwiz/nativescript-toasty#36]
According to documentation, backgroundColor removes android native look 'n feel for toasts.
`On Android this currently removes the default Toast rounded borders.`

Setting backgroundColor value to double quotes "" during initialization allows the use of native android toast. However, setting value to null will make toast itself disappear.

This is rather confusing and one can't find the solution without a bit of testing.

**Comment by bradmartin** [comment]
This will be closed with the `4.0.0` release for NS7 soon.
