### ISSUE TITLE
NativeScript 7 update

### ISSUE THREAD

**Issue by kaanguru** [triniwiz/nativescript-toasty#44]
Is NativeScript 7 update coming anytime soon?

https://nativescript.org/blog/nativescript-7-for-plugin-authors/

**Comment by jalberto-ghub** [comment]
Hi @triniwiz I can see you have made the changes for the upgrade to 7.0. but they are not published on npm yet (latest npm is 3.0.0-alpha2). Do you know when are you planing to publish the new version?

Regards,

**Comment by PhilippS93** [comment]
here is a published workaround https://www.npmjs.com/package/nativescript-toasty-ns-7

**Comment by jalberto-ghub** [comment]
There does not seem to be a published label for N7 on NPM. Here is the result of checking the registry
```
>npm v nativescript-toasty

nativescript-toasty@3.0.0-alpha.2 | MIT | deps: none | versions: 16
NativeScript toast plugin
https://github.com/triniwiz/nativescript-toasty

keywords: NativeScript, JavaScript, Android, iOS, toast

dist
.tarball: https://registry.npmjs.org/nativescript-toasty/-/nativescript-toasty-3.0.0-alpha.2.tgz
.shasum: 3fcc1328e944f6671b88752ff41e4de68d244647
.integrity: sha512-GGYdiPAhGbwITmxnkWL4oCYW//ExR/ir38oqzbAFI7uZD+1NkD7FcCh68vpOvUpHmB09SqeHI30aeuBcTndB+w==
.unpackedSize: 40.2 kB

maintainers:
- triniwiz <fortune.osei@yahoo.com>

dist-tags:
latest: 3.0.0-alpha.2

published 9 months ago by triniwiz <fortune.osei@yahoo.com>
```

**Comment by triniwiz** [comment]
Working on publishing all the new goodies 😃

**Comment by romandrahan** [comment]
@triniwiz, sorry, did you have time to publish the update?

**Comment by phenric** [comment]
@triniwiz Any news? 😃
If you need help, I'm here ✋

**Comment by bifrost-bridge** [comment]
@triniwiz Do you know when the NS7 version is going to be published?  Or should people be using the [workaround](https://github.com/triniwiz/nativescript-toasty/issues/44#issuecomment-696085183) posted by @PhilippS93?

**Comment by triniwiz** [comment]
You can grab it @ https://www.npmjs.com/package/@triniwiz/nativescript-toasty the repo is currently not live

**Comment by triniwiz** [comment]
It's `@triniwiz/nativescript-toasty` feel free to update
