### ISSUE TITLE
NativeScript 3

### ISSUE THREAD

**Issue by zsolt-racz** [triniwiz/nativescript-toasty#5]
Great plugin, but could you please add compatibility for NativeScript 3?

**Comment by triniwiz** [comment]
The plugin should work fine in 3.0

**Comment by bradmartin** [comment]
Confirmed - use it in 2 production apps running 3.0.1

**Comment by zsolt-racz** [comment]
Thank you, it works for me with 3.0 as well. I've just seen version 2.x in the package.json as a dependency, so I tought it wouldn't work with 3. But fortunately I was wrong.
