### ISSUE TITLE
App Crash on IOS 14.4

### ISSUE THREAD

**Issue by jitendraP-ashutec** [triniwiz/nativescript-toasty#52]
I am getting the below error on iOS14.4 , Nativescript: 7.0.10. 
It is working fine in android 11.

ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() Label(577)
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() Label(577)
at
ZoneAwareError(file: node_modules/@nativescript/zone-js/zone-nativescript.js:1298:0)

**Comment by triniwiz** [comment]
1. Package version
2. Code sample

**Comment by jitendraP-ashutec** [comment]
I am using @triniwiz/nativescript-toasty - 4.1.3 version 


```
/ / sample code
const text = 'message';
new Toasty({ text }).show()
````

**Comment by jitendraP-ashutec** [comment]
@triniwiz  It was my mistake. This package is working on ios 14.4.
